export enum ActivityType {
    // Authentication related
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    FAILED_LOGIN_ATTEMPT = 'FAILED_LOGIN_ATTEMPT',
    
    // Wallet related
    WALLET_LINKED = 'WALLET_LINKED',
    WALLET_UNLINKED = 'WALLET_UNLINKED',
    
    // Transaction related
    TRANSACTION_CREATED = 'TRANSACTION_CREATED',
    TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
    TRANSACTION_FAILED = 'TRANSACTION_FAILED',
    
    // General
    PROFILE_UPDATED = 'PROFILE_UPDATED',
    SETTINGS_CHANGED = 'SETTINGS_CHANGED'
  }